import React, { useState } from "react";

export default function test() {
  const [data, setData] = useState([
    {
      registered: new Date(),
      name: "Mark Otto	",
      sale: "New",
      phone: "12312321",
      email: "test@gmail.com",
      balance: 100,
      deposit: 50,
      manager: "John",
      affiliates: "Candy Land",
    },
    {
      registered: new Date(),
      name: "Jane Doe	",
      sale: "New",
      phone: "12312321",
      email: "test@gmail.com",
      balance: 100,
      deposit: 50,
      manager: "John",
      affiliates: "Candy Land",
    },
    {
      registered: new Date(),
      name: "Alice Johnson	",
      sale: "New",
      phone: "12312321",
      email: "test@gmail.com",
      balance: 100,
      deposit: 50,
      manager: "John",
      affiliates: "Candy Land",
    },
    {
      registered: new Date(),
      name: "Michael Smith	",
      sale: "New",
      phone: "12312321",
      email: "test@gmail.com",
      balance: 100,
      deposit: 50,
      manager: "John",
      affiliates: "Candy Land",
    },
    {
      registered: new Date(),
      name: "Susan Lee	",
      sale: "New",
      phone: "12312321",
      email: "test@gmail.com",
      balance: 100,
      deposit: 50,
      manager: "John",
      affiliates: "Candy Land",
    },
    {
      registered: new Date(),
      name: "David Brown	",
      sale: "New",
      phone: "12312321",
      email: "test@gmail.com",
      balance: 100,
      deposit: 50,
      manager: "John",
      affiliates: "Candy Land",
    },
    {
      registered: new Date(),
      name: "Lisa Johnson	",
      sale: "New",
      phone: "12312321",
      email: "test@gmail.com",
      balance: 100,
      deposit: 50,
      manager: "John",
      affiliates: "Candy Land",
    },
    {
      registered: new Date(),
      name: "John Smith	",
      sale: "New",
      phone: "12312321",
      email: "test@gmail.com",
      balance: 100,
      deposit: 50,
      manager: "John",
      affiliates: "Candy Land",
    },
    {
      registered: new Date(),
      name: "Mary Taylor	",
      sale: "New",
      phone: "12312321",
      email: "test@gmail.com",
      balance: 100,
      deposit: 50,
      manager: "John",
      affiliates: "Candy Land",
    },
    {
      registered: new Date(),
      name: "Robert Anderson	",
      sale: "New",
      phone: "12312321",
      email: "test@gmail.com",
      balance: 100,
      deposit: 50,
      manager: "John",
      affiliates: "Candy Land",
    },
  ]);
  return <div>{data}</div>;
}
